---
title: "Figures 2-4"
output: html_document
---

```{r include=FALSE}
rm(list=ls())

# 1a Declare root directory, folder locations and load essential stuff
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(functions.folder,'script_initiate.R'))
```

```{r user-input2, include=FALSE}
# load data
dat = read.csv(paste0(model.output.folder,'/','results_',years_analysis[1],'_',end_year,'.csv'))
```

# Plot Figure 2
```{r user-input9}
  p=ggplot(data=subset(dat, sex=='All' & age=='All' & percentile=='All')) +
      geom_point(aes(x=lag.factor,y=rr-1,color=class),size=2,shape=16,position=position_dodge(0.7)) +    
      geom_errorbar(aes(x=lag.factor,ymin=rr.ll-1,ymax=rr.ul-1,color=class),width=.5,size=0.5,position=position_dodge(0.7)) +
      geom_hline(yintercept=0,linetype='dotted') +
      scale_color_manual(values=colors.wind.class[c(3,1)]) +
      # coord_flip() +
      guides(color=guide_legend(title="",nrow=1)) +
      scale_y_continuous(labels=scales::percent_format(accuracy=1)) +
      xlab('Lag (months after exposure)') + ylab('Percentage change in death rates\nassociated with exposure') +
      facet_wrap(~cause) +
      theme_bw() + 
      theme(text = element_text(size = 10),
                         panel.grid.major = element_blank(),axis.text.x = element_text(angle=0), axis.text.y = element_text(size=12),
                         plot.title = element_text(hjust = 0.5),panel.background = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                         panel.border = element_rect(colour = "black"),strip.background = element_blank(),
                         legend.position = 'bottom',legend.justification='center',
                         legend.background = element_rect(fill="white", size=.5, linetype="dotted"))
  
    p
```

# Plot Figure 3
```{r user-input12}
  p=ggplot(data=subset(dat, class=='Tropical cyclones' & percentile=='All' & sex=='All')) +
      geom_point(aes(x=lag.factor,y=rr-1,color=age),size=2,shape=16,position=position_dodge(0.7)) +    
      geom_errorbar(aes(x=lag.factor,ymin=rr.ll-1,ymax=rr.ul-1,color=age),width=.5,size=0.5,position=position_dodge(0.7)) +
      geom_hline(yintercept=0,linetype='dotted') +
      scale_color_manual(values=colors.age) +
      # coord_flip() +
      guides(color=guide_legend(title="",nrow=1)) +
      scale_y_continuous(labels=scales::percent_format(accuracy=1)) +
      xlab('Lag (months after exposure)') + ylab('Percentage change in death rates\nassociated with tropical cyclone exposure') +
      facet_wrap(~cause) +
      theme_bw() + 
      theme(text = element_text(size = 10),
                         panel.grid.major = element_blank(),axis.text.x = element_text(angle=0), axis.text.y = element_text(size=12),
                         plot.title = element_text(hjust = 0.5),panel.background = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                         panel.border = element_rect(colour = "black"),strip.background = element_blank(),
                         legend.position = 'bottom',legend.justification='center',
                         legend.background = element_rect(fill="white", size=.5, linetype="dotted"))

    p
```

## Plot Figure 4
```{r user-input13}
  p=ggplot(data=subset(dat, age=='All' & class=='Tropical cyclones' & sex=='All')) +
      geom_point(aes(x=lag.factor,y=rr-1,color=tertile),size=2,shape=16,position=position_dodge(0.7)) +    
      geom_errorbar(aes(x=lag.factor,ymin=rr.ll-1,ymax=rr.ul-1,color=tertile),width=.5,size=0.5,position=position_dodge(0.7)) +
      geom_hline(yintercept=0,linetype='dotted') +
      scale_color_manual(values=colorpalette.svi.plot) +
      # coord_flip() +
      guides(color=guide_legend(title="",nrow=1)) +
      scale_y_continuous(labels=scales::percent_format(accuracy=1)) +
      xlab('Lag (months after exposure)') + ylab('Percentage change in death rates\nassociated with tropical cyclone exposure') +
      facet_wrap(~cause) +
      theme_bw() + 
      theme(text = element_text(size = 10),
                         panel.grid.major = element_blank(),axis.text.x = element_text(angle=0), axis.text.y = element_text(size=12),
                         plot.title = element_text(hjust = 0.5),panel.background = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                         panel.border = element_rect(colour = "black"),strip.background = element_blank(),
                         legend.position = 'bottom',legend.justification='center',
                         legend.background = element_rect(fill="white", size=.5, linetype="dotted"))
  
    p
```